sudo: required

language: node_js
node_js:
  - "6"

before_install:
  - sudo apt-get update && sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker --version
install:
  - npm install -g eslint@3.19.0

services:
  - docker

after_success:
  - docker ps -a
  - docker images -a

env:
  matrix:
    - TEST_IMG=node
    - TEST_IMG=dotnet
    - TEST_IMG=jvm
    - TEST_IMG=python
    - TEST_IMG=ruby
    - TEST_IMG=alt
    - TEST_IMG=rust
    - TEST_IMG=julia
    - TEST_IMG=systems
    - TEST_IMG=dart
    - TEST_IMG=crystal
    - TEST_IMG=ocaml
    - TEST_IMG=swift
    - TEST_IMG=haskell
    - TEST_IMG=objc
    - TEST_IMG=go
    - TEST_IMG=lua
    - TEST_IMG=java
    - TEST_IMG=esolangs
    - TEST_IMG=chapel

script:
  - eslint '**/*.js'
  - cp docker/${TEST_IMG}.docker ./Dockerfile
  - if docker pull codewars/${TEST_IMG}-runner; then
      docker build --cache-from codewars/${TEST_IMG}-runner -t codewars/${TEST_IMG}-runner .;
    else
      docker build -t codewars/${TEST_IMG}-runner .;
    fi
